//Cart Actions

export const VIEW_CART_ITEMS = "VIEW_CART_ITEMS";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const INCREASE_QUANTITY_BY_ONE = "INCREASE_QUANTITY_BY_ONE";
export const DECREASE_QUANTITY_BY_ONE = "DECREASE_QUANTITY_BY_ONE";
// export const CALCULATE_TOTAL = 'CALCULATE_TOTAL';
